config/routes.rb
Rails.application.routes.draw do
  get 'payments/create'
  get 'payments/show/:id', to: 'payments#show', as: :payments_show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  def create
    @payment = OpenStruct.new(id: 200)
    StripePaymentJob.perform_later('process payment later')
  end
  
  def show
    logger.info params
    render json: { result: 'success', receipt_id: 'CXM4873'}
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Poll</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/payments/create.html.erb
<h1>Payments#create</h1>

<div id='loader' data-url="<%= payments_show_url(@payment.id) %>">
	<img src="http://preloaders.net/preloaders/712/Floating%20rays.gif"/>
</div>

<div id='status'>Payment is being processed. Please wait...</div>